/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentpayments;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ClassFiles.MyConn;
import java.sql.ResultSet;

/**
 *
 * @author dinis
 */
public class addNewCoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form addNewCoursePanel
     */
    public addNewCoursePanel() {
        initComponents();
        
        idIncrement();
    }

    public void clearFields() {
        courseFeeTxtBox.setText("");
        courseTitleTxtBox.setText("");
        durationTxtBox2.setText("");
        buttonGroup1.clearSelection();
    }
    
    public void idIncrement(){
    
        int id = 1;
        try {
            String getId = "Select * from course";
            ResultSet rs = MyConn.search(getId);
            while (rs.next()) {                
                id = Integer.parseInt(rs.getString("CourseID"));
            }
            id++;
            courseIDTxtBox.setText(String.valueOf(id));
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        courseIDTxtBox.setEditable(false);
        
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        courseIDTxtBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        courseTitleTxtBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        durationTxtBox2 = new javax.swing.JTextField();
        courseFeeTxtBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        yearlyradioBtn = new javax.swing.JRadioButton();
        monthlyRadioBtn = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        saveCourseBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "ADD COURSE PANEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("COURSE ID:-");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 30));

        courseIDTxtBox.setBackground(new java.awt.Color(204, 204, 204));
        courseIDTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        courseIDTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        add(courseIDTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 430, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("COURSE TITLE:-");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, 30));

        courseTitleTxtBox.setBackground(new java.awt.Color(204, 204, 204));
        courseTitleTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        courseTitleTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        add(courseTitleTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 430, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DURATION:-");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 30));

        durationTxtBox2.setBackground(new java.awt.Color(204, 204, 204));
        durationTxtBox2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        durationTxtBox2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        add(durationTxtBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 430, 30));

        courseFeeTxtBox.setBackground(new java.awt.Color(204, 204, 204));
        courseFeeTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        courseFeeTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        courseFeeTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                courseFeeTxtBoxKeyTyped(evt);
            }
        });
        add(courseFeeTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 430, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("NEED TO PAY:-");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, 30));

        yearlyradioBtn.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(yearlyradioBtn);
        yearlyradioBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        yearlyradioBtn.setText("YEARLY");
        add(yearlyradioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, 30));

        monthlyRadioBtn.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(monthlyRadioBtn);
        monthlyRadioBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        monthlyRadioBtn.setText("MONTHLY");
        add(monthlyRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("COURSE FEE:-");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 30));

        saveCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
        saveCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveCourseBtn.setText("SAVE COURSE");
        saveCourseBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        saveCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveCourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveCourseBtnMouseExited(evt);
            }
        });
        saveCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCourseBtnActionPerformed(evt);
            }
        });
        add(saveCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 570, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void saveCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveCourseBtnMouseEntered
        saveCourseBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_saveCourseBtnMouseEntered

    private void saveCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveCourseBtnMouseExited
        saveCourseBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_saveCourseBtnMouseExited

    private void saveCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCourseBtnActionPerformed
        try {
            if (courseIDTxtBox.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter course ID");
                courseIDTxtBox.grabFocus();
            } else if (courseTitleTxtBox.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter course title");
                courseTitleTxtBox.grabFocus();
            } else if (courseTitleTxtBox.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter course title");
                courseTitleTxtBox.grabFocus();

            } else {
                JFrame f = new JFrame();
                if (JOptionPane.showConfirmDialog(f, "Are all the deatils correcr?") == JOptionPane.YES_NO_OPTION) {

                    String needToPay = "";
                    if (yearlyradioBtn.isSelected()) {
                        needToPay = "Yearly";
                    } else if (monthlyRadioBtn.isSelected()) {
                        needToPay = "Monthly";
                    }
                    String id = "STD-12345";
                    String saveCourse = "Insert into course(CourseID, CourseTitle, Duration, Fee, NeedToPay, student_StudentID) values ('" + courseIDTxtBox.getText() + "', '" + courseTitleTxtBox.getText() + "', '" + courseFeeTxtBox.getText() + "', '"+durationTxtBox2.getText()+"', '" + needToPay + "', '"+id+"')";
                    MyConn.save(saveCourse);
                    JOptionPane.showMessageDialog(null, "Save Successful");
                    clearFields();
                    idIncrement();
                } else {
                    JOptionPane.showMessageDialog(null, "Save Unsuccessful");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveCourseBtnActionPerformed

    private void courseFeeTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseFeeTxtBoxKeyTyped


    }//GEN-LAST:event_courseFeeTxtBoxKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField courseFeeTxtBox;
    private javax.swing.JTextField courseIDTxtBox;
    private javax.swing.JTextField courseTitleTxtBox;
    private javax.swing.JTextField durationTxtBox2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton monthlyRadioBtn;
    private javax.swing.JButton saveCourseBtn;
    private javax.swing.JRadioButton yearlyradioBtn;
    // End of variables declaration//GEN-END:variables
}
