/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentpayments;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author dinis
 */
public class adminProfile extends javax.swing.JFrame {

    /**
     * Creates new form adminProfile
     */
    public adminProfile(String admID) {
        initComponents();

        admIDLable.setText(admID);
        date();
        time();
    }

    // This method vill show the date to the user
    public void date() {
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        dateLable.setText(df.format(d));
    }

    //This method will show the current time to the user
    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        admIDLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        showOptionsPane = new javax.swing.JDesktopPane();
        addCourseBtn = new javax.swing.JButton();
        viewstdCourseBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        updateCourseBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        clearOptionsPane = new javax.swing.JButton();
        removeCourseBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        chagePWdBtn = new javax.swing.JButton();
        closeBtn1 = new javax.swing.JButton();
        logOutBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel1.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        timeLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setToolTipText("Time");
        timeLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel1.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ADMIN PROFILE :-");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 160, 20));

        admIDLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        admIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admIDLable.setText("ADMIN ID");
        jPanel1.add(admIDLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 160, 20));

        jLabel1.setToolTipText("Student ID");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 340, 20));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 3, 3), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showOptionsPane.setToolTipText("Option Panel Area");

        javax.swing.GroupLayout showOptionsPaneLayout = new javax.swing.GroupLayout(showOptionsPane);
        showOptionsPane.setLayout(showOptionsPaneLayout);
        showOptionsPaneLayout.setHorizontalGroup(
            showOptionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        showOptionsPaneLayout.setVerticalGroup(
            showOptionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel3.add(showOptionsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 450));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 610, 470));

        addCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
        addCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addCourseBtn.setText("ADD NEW COURSE");
        addCourseBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addCourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addCourseBtnMouseExited(evt);
            }
        });
        addCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 560, 60));

        viewstdCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
        viewstdCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewstdCourseBtn.setText("VIEW STUDENTS AND COURSES");
        viewstdCourseBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        viewstdCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewstdCourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewstdCourseBtnMouseExited(evt);
            }
        });
        viewstdCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstdCourseBtnActionPerformed(evt);
            }
        });
        jPanel2.add(viewstdCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 560, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("OPTIONS");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 560, 20));

        updateCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
        updateCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateCourseBtn.setText("UPDATE A COURSE");
        updateCourseBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        updateCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateCourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateCourseBtnMouseExited(evt);
            }
        });
        updateCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCourseBtnActionPerformed(evt);
            }
        });
        jPanel2.add(updateCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 560, 60));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 360, 10));

        clearOptionsPane.setBackground(new java.awt.Color(204, 204, 204));
        clearOptionsPane.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearOptionsPane.setText("CLEAR THE OPTION PANEL AREA");
        clearOptionsPane.setToolTipText("Close App");
        clearOptionsPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
        clearOptionsPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearOptionsPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearOptionsPaneMouseExited(evt);
            }
        });
        clearOptionsPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOptionsPaneActionPerformed(evt);
            }
        });
        jPanel2.add(clearOptionsPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 560, 30));

        removeCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
        removeCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        removeCourseBtn.setText("REMOVE A COURSE");
        removeCourseBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        removeCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                removeCourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeCourseBtnMouseExited(evt);
            }
        });
        removeCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCourseBtnActionPerformed(evt);
            }
        });
        jPanel2.add(removeCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 560, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1220, 500));

        backBtn.setBackground(new java.awt.Color(204, 204, 204));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_left_arrow_24px_2.png"))); // NOI18N
        backBtn.setToolTipText("Back");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 100, 20));

        chagePWdBtn.setBackground(new java.awt.Color(204, 204, 204));
        chagePWdBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        chagePWdBtn.setText("CHANGE PASSWORD");
        chagePWdBtn.setToolTipText("LogOut");
        chagePWdBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 2, true));
        chagePWdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chagePWdBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chagePWdBtnMouseExited(evt);
            }
        });
        chagePWdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chagePWdBtnActionPerformed(evt);
            }
        });
        jPanel1.add(chagePWdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 370, 20));

        closeBtn1.setBackground(new java.awt.Color(204, 204, 204));
        closeBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        closeBtn1.setText("CLOSE");
        closeBtn1.setToolTipText("Close App");
        closeBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
        closeBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtn1MouseExited(evt);
            }
        });
        closeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(closeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, 100, 20));

        logOutBtn1.setBackground(new java.awt.Color(204, 204, 204));
        logOutBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logOutBtn1.setText("LOG OUT");
        logOutBtn1.setToolTipText("LogOut");
        logOutBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
        logOutBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logOutBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logOutBtn1MouseExited(evt);
            }
        });
        logOutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(logOutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCourseBtnMouseEntered
        addCourseBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_addCourseBtnMouseEntered

    private void addCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCourseBtnMouseExited
        addCourseBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_addCourseBtnMouseExited

    private void addCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseBtnActionPerformed
        showOptionsPane.removeAll();

        addNewCoursePanel addCoursePanel = new addNewCoursePanel();
        showOptionsPane.add(addCoursePanel);
        addCoursePanel.setLocation(0, 0);
        addCoursePanel.setSize(showOptionsPane.getSize());
    }//GEN-LAST:event_addCourseBtnActionPerformed

    private void viewstdCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewstdCourseBtnMouseEntered
        viewstdCourseBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_viewstdCourseBtnMouseEntered

    private void viewstdCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewstdCourseBtnMouseExited
        viewstdCourseBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_viewstdCourseBtnMouseExited

    private void viewstdCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstdCourseBtnActionPerformed
        showOptionsPane.removeAll();

        viewStdCourses viewPanel = new viewStdCourses();
        showOptionsPane.add(viewPanel);
        viewPanel.setLocation(0, 0);
        viewPanel.setSize(showOptionsPane.getSize());
    }//GEN-LAST:event_viewstdCourseBtnActionPerformed

    private void updateCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCourseBtnMouseEntered
        updateCourseBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_updateCourseBtnMouseEntered

    private void updateCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCourseBtnMouseExited
        updateCourseBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_updateCourseBtnMouseExited

    private void updateCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCourseBtnActionPerformed
        showOptionsPane.removeAll();

        updateCoursePanel1 updateCoursePanel = new updateCoursePanel1();
        showOptionsPane.add(updateCoursePanel);
        updateCoursePanel.setLocation(0, 0);
        updateCoursePanel.setSize(showOptionsPane.getSize());
    }//GEN-LAST:event_updateCourseBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(Color.red);
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void chagePWdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chagePWdBtnMouseEntered
        chagePWdBtn.setBackground(Color.red);
    }//GEN-LAST:event_chagePWdBtnMouseEntered

    private void chagePWdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chagePWdBtnMouseExited
        chagePWdBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_chagePWdBtnMouseExited

    private void chagePWdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chagePWdBtnActionPerformed
        new ForgotPasswordFrame(admIDLable.getText()).setVisible(true);
    }//GEN-LAST:event_chagePWdBtnActionPerformed

    private void closeBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseEntered
        closeBtn1.setBackground(Color.red);
    }//GEN-LAST:event_closeBtn1MouseEntered

    private void closeBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseExited
        closeBtn1.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_closeBtn1MouseExited

    private void closeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtn1ActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "DO YOU WANT TO EXIT") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeBtn1ActionPerformed

    private void clearOptionsPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearOptionsPaneMouseEntered
        closeBtn1.setBackground(Color.red);
    }//GEN-LAST:event_clearOptionsPaneMouseEntered

    private void clearOptionsPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearOptionsPaneMouseExited
        closeBtn1.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_clearOptionsPaneMouseExited

    private void clearOptionsPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearOptionsPaneActionPerformed
        showOptionsPane.removeAll();
    }//GEN-LAST:event_clearOptionsPaneActionPerformed

    private void removeCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCourseBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCourseBtnMouseEntered

    private void removeCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCourseBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_removeCourseBtnMouseExited

    private void removeCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCourseBtnActionPerformed
        showOptionsPane.removeAll();

        deleteCoursePanel deleteCoursePanel = new deleteCoursePanel();
        showOptionsPane.add(deleteCoursePanel);
        deleteCoursePanel.setLocation(0, 0);
        deleteCoursePanel.setSize(showOptionsPane.getSize());
    }//GEN-LAST:event_removeCourseBtnActionPerformed

    private void logOutBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutBtn1MouseEntered

    private void logOutBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutBtn1MouseExited

    private void logOutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminProfile("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseBtn;
    private javax.swing.JLabel admIDLable;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton chagePWdBtn;
    private javax.swing.JButton clearOptionsPane;
    private javax.swing.JButton closeBtn1;
    private javax.swing.JLabel dateLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logOutBtn1;
    private javax.swing.JButton removeCourseBtn;
    private javax.swing.JDesktopPane showOptionsPane;
    private javax.swing.JLabel timeLable;
    private javax.swing.JButton updateCourseBtn;
    private javax.swing.JButton viewstdCourseBtn;
    // End of variables declaration//GEN-END:variables
}
