/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentpayments;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ClassFiles.MyConn;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class deleteCoursePanel extends javax.swing.JPanel {

    /**
     * Creates new form addNewCoursePanel
     */
    public deleteCoursePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        deleteCourseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseListTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "DELETE COURSE PANEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
        deleteCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteCourseBtn.setText("DELETE COURSE");
        deleteCourseBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(153, 0, 0)));
        deleteCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteCourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteCourseBtnMouseExited(evt);
            }
        });
        deleteCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseBtnActionPerformed(evt);
            }
        });
        add(deleteCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 570, 50));

        courseListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Title", "Duration", "Need to Pay"
            }
        ));
        jScrollPane1.setViewportView(courseListTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 330));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCourseBtnMouseEntered
        deleteCourseBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_deleteCourseBtnMouseEntered

    private void deleteCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteCourseBtnMouseExited
        deleteCourseBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_deleteCourseBtnMouseExited

    private void deleteCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseBtnActionPerformed
        try {
            
            DefaultTableModel df = (DefaultTableModel) courseListTable.getModel();
            
            if (courseListTable.getSelectedRowCount() == 1) {
                
                JFrame f = new JFrame();
                if (JOptionPane.showConfirmDialog(f, "Do you want to delete this?") == JOptionPane.YES_NO_OPTION) {
                    
                    String courseTitle = df.getValueAt(courseListTable.getSelectedRow(), 0).toString();
                    
                    String delete = "Delete from course where CourseID = '" + courseTitle + "'";
                    MyConn.save(delete);
                    df.removeRow(courseListTable.getSelectedRow());
                    JOptionPane.showMessageDialog(null, "SuccessFully Deleted");
                    
                } else {
                    JOptionPane.showMessageDialog(null, "UnsuccessFull");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please select a course to Delete");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteCourseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable courseListTable;
    private javax.swing.JButton deleteCourseBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
