/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentpayments;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ClassFiles.MyConn;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author dinis
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uNameTxtBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        forgotPwdBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        pwdTxtBox = new javax.swing.JPasswordField();
        viewPwdChkBox = new javax.swing.JCheckBox();
        clearBtn1 = new javax.swing.JButton();
        directToRegisterLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN PAYMENT SYSTEM");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 890, 40));

        uNameTxtBox.setBackground(new java.awt.Color(204, 204, 204));
        uNameTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uNameTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel2.add(uNameTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 810, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("PASSWORD :-");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 750, 20));

        forgotPwdBtn.setBackground(new java.awt.Color(153, 153, 153));
        forgotPwdBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forgotPwdBtn.setText("FORGOT PASSWORD");
        forgotPwdBtn.setToolTipText("Click to reset the password");
        forgotPwdBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        forgotPwdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotPwdBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                forgotPwdBtnMouseExited(evt);
            }
        });
        forgotPwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPwdBtnActionPerformed(evt);
            }
        });
        jPanel2.add(forgotPwdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 170, 30));

        loginBtn.setBackground(new java.awt.Color(153, 153, 153));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginBtn.setText("LOGIN");
        loginBtn.setToolTipText("Click to login");
        loginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel2.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("USERNAME :-");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 810, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 520, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 520, 10));

        pwdTxtBox.setBackground(new java.awt.Color(204, 204, 204));
        pwdTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pwdTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel2.add(pwdTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 810, 50));

        viewPwdChkBox.setBackground(new java.awt.Color(204, 204, 204));
        viewPwdChkBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewPwdChkBox.setText("VIEW ");
        viewPwdChkBox.setToolTipText("View Password");
        viewPwdChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPwdChkBoxActionPerformed(evt);
            }
        });
        jPanel2.add(viewPwdChkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 60, -1));

        clearBtn1.setBackground(new java.awt.Color(153, 153, 153));
        clearBtn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearBtn1.setText("CLEAR");
        clearBtn1.setToolTipText("Clear the text fields");
        clearBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        clearBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clearBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clearBtn1MouseExited(evt);
            }
        });
        jPanel2.add(clearBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 170, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 56, 890, 380));

        directToRegisterLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        directToRegisterLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        directToRegisterLbl.setText("IF YOU DON'T HAVE AN ACCOUNT CLICK HERE TO REGISTER");
        directToRegisterLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                directToRegisterLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                directToRegisterLblMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                directToRegisterLblMouseExited(evt);
            }
        });
        jPanel1.add(directToRegisterLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 450, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 450, 10));

        closeBtn.setBackground(new java.awt.Color(153, 153, 153));
        closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        closeBtn.setText("CLOSE");
        closeBtn.setToolTipText("Close App");
        closeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(closeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "DO YOU WANT TO EXIT") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeBtnActionPerformed

    private void forgotPwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPwdBtnActionPerformed
        new ForgotPasswordFrame("").setVisible(true);
    }//GEN-LAST:event_forgotPwdBtnActionPerformed

    private void viewPwdChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPwdChkBoxActionPerformed
        if (viewPwdChkBox.isSelected()) {
            if (pwdTxtBox.getEchoChar() == '*') {

                pwdTxtBox.setEchoChar((char) 0);

            } else {
                pwdTxtBox.setEchoChar('*');

            }
        } else {
            if (pwdTxtBox.getEchoChar() == '*') {

                pwdTxtBox.setEchoChar((char) 0);

            } else {
                pwdTxtBox.setEchoChar('*');

            }
        }
    }//GEN-LAST:event_viewPwdChkBoxActionPerformed

    private void directToRegisterLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directToRegisterLblMouseClicked
        this.dispose();
        new StudentRegiter().setVisible(true);
    }//GEN-LAST:event_directToRegisterLblMouseClicked

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_loginBtnMouseExited

    private void clearBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtn1MouseEntered
        clearBtn1.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_clearBtn1MouseEntered

    private void clearBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtn1MouseExited
        clearBtn1.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_clearBtn1MouseExited

    private void forgotPwdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPwdBtnMouseEntered
        forgotPwdBtn.setBackground(new Color(242, 242, 242));
    }//GEN-LAST:event_forgotPwdBtnMouseEntered

    private void forgotPwdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPwdBtnMouseExited
        forgotPwdBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_forgotPwdBtnMouseExited

    private void directToRegisterLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directToRegisterLblMouseEntered
        directToRegisterLbl.setForeground(new Color(204, 204, 204));
    }//GEN-LAST:event_directToRegisterLblMouseEntered

    private void directToRegisterLblMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directToRegisterLblMouseExited
        directToRegisterLbl.setForeground(Color.BLACK);
    }//GEN-LAST:event_directToRegisterLblMouseExited

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        closeBtn.setBackground(Color.red);
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        closeBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_closeBtnMouseExited

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        try {
            
            String tblName = "";
            String id = "";
            
            if (uNameTxtBox.getText().contains("ADM")) {
                tblName = "admin";
                id = "adminID";
            } else if(uNameTxtBox.getText().contains("STD")){
                tblName = "student";
                id = "StudentID";
            }else{
                JOptionPane.showMessageDialog(null, "Error with UserName");
            }
            
            String getUserID = "Select * from "+tblName+" where "+id+" = '"+uNameTxtBox.getText()+"'";
            ResultSet rs = MyConn.search(getUserID);
            
            while (rs.next()) {                
                if (pwdTxtBox.getText().equals(rs.getString("password"))) {
                    
                    JOptionPane.showMessageDialog(null, "Login Successfull");
                    if (tblName.equals("student")) {
                        new StudentProfile(uNameTxtBox.getText()).setVisible(true);
                    } else if(tblName.equals("admin")){
                        new adminProfile(uNameTxtBox.getText()).setVisible(true);
                    }
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Login Unsuccessfull");
                }
            }
    
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn1;
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel directToRegisterLbl;
    private javax.swing.JButton forgotPwdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField pwdTxtBox;
    private javax.swing.JTextField uNameTxtBox;
    private javax.swing.JCheckBox viewPwdChkBox;
    // End of variables declaration//GEN-END:variables
}
