/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentpayments;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.sql.ResultSet;
import ClassFiles.*;
import java.util.HashMap;
import java.util.Random;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dinis
 */
public class MakePaymentsFrame extends javax.swing.JFrame {

    /**
     * Creates new form MakePaymentsFrame
     */
    int ranVal = 0;
    int otp = 0;

    public MakePaymentsFrame() {
        initComponents();

        date();
        time();

        loadCourses();
        coursesCmbBox.setSelectedItem("Course List");
    }

    // This method vill show the date to the user
    public void date() {
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        dateLable.setText(df.format(d));
    }

    //This method will show the current time to the user
    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void randomValueGen() {

        Random random = new Random();
        ranVal = random.nextInt(10000);
    }

    public void otpGenarator() {

        Random random = new Random();
        ranVal = random.nextInt(1000);
    }

    public void loadCourses() {

        try {
            String getCourse = "select * from course";
            ResultSet rs = MyConn.search(getCourse);
            coursesCmbBox.addItem("Course List");

            while (rs.next()) {
                coursesCmbBox.addItem(rs.getString("CourseTitle"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setTotal() {
        DefaultTableModel df = (DefaultTableModel) cartTable.getModel();
        int rowC = df.getRowCount();
        double total = 0;
        for (int i = 0; i < rowC; i++) {
            total += Double.parseDouble(df.getValueAt(i, 1).toString());
            subTotalTxtBox.setText(String.valueOf(total));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dateLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        feeTxtBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        payBtn = new javax.swing.JButton();
        coursesCmbBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        removeCourseBtn = new javax.swing.JButton();
        addToPayBtn1 = new javax.swing.JButton();
        clearAllBtn = new javax.swing.JButton();
        subTotalTxtBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        holderNameTxtBox = new javax.swing.JTextField();
        cardNoTxtBox = new javax.swing.JTextField();
        exDateTxtBox = new javax.swing.JTextField();
        cvvTxtBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        visaCardRadioBtn = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        masterCardRadioBtn = new javax.swing.JRadioButton();
        getOtpBTn = new javax.swing.JButton();
        otpTxtBox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        closeBtn1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        stdIDLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153), new java.awt.Color(102, 102, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel1.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        timeLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setToolTipText("Time");
        timeLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel1.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 20));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 3, 3), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Amount"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    jScrollPane1.setViewportView(cartTable);

    jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 520, 180));

    feeTxtBox.setEditable(false);
    feeTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
    feeTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
    jPanel2.add(feeTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 520, 30));

    jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel8.setText("SELECT A COURSE:-");
    jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 420, 20));

    payBtn.setBackground(new java.awt.Color(204, 204, 204));
    payBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    payBtn.setText("PAY");
    payBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
    payBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            payBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            payBtnMouseExited(evt);
        }
    });
    payBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            payBtnActionPerformed(evt);
        }
    });
    jPanel2.add(payBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 640, 60));

    coursesCmbBox.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            coursesCmbBoxItemStateChanged(evt);
        }
    });
    jPanel2.add(coursesCmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 520, 30));

    jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel9.setText("FEE :-");
    jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 430, 20));

    removeCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
    removeCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    removeCourseBtn.setText("REMOVE COURSE FROM PAY");
    removeCourseBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(153, 0, 0)));
    removeCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            removeCourseBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            removeCourseBtnMouseExited(evt);
        }
    });
    removeCourseBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            removeCourseBtnActionPerformed(evt);
        }
    });
    jPanel2.add(removeCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 250, 30));

    addToPayBtn1.setBackground(new java.awt.Color(204, 204, 204));
    addToPayBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    addToPayBtn1.setText("ADD TO PAY");
    addToPayBtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 102)));
    addToPayBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            addToPayBtn1MouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            addToPayBtn1MouseExited(evt);
        }
    });
    addToPayBtn1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            addToPayBtn1ActionPerformed(evt);
        }
    });
    jPanel2.add(addToPayBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 520, -1));

    clearAllBtn.setBackground(new java.awt.Color(204, 204, 204));
    clearAllBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    clearAllBtn.setText("CLEAR ALL");
    clearAllBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(153, 0, 0)));
    clearAllBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            clearAllBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            clearAllBtnMouseExited(evt);
        }
    });
    clearAllBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            clearAllBtnActionPerformed(evt);
        }
    });
    jPanel2.add(clearAllBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 250, 30));

    subTotalTxtBox.setEditable(false);
    subTotalTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
    subTotalTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
    jPanel2.add(subTotalTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 530, 40));

    jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel10.setText("SUBTOTAL:-");
    jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 430, 30));

    jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
    jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1200, 10));

    jPanel3.setBackground(new java.awt.Color(204, 204, 204));
    jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 102), new java.awt.Color(0, 0, 0)));
    jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    holderNameTxtBox.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
    holderNameTxtBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            holderNameTxtBoxActionPerformed(evt);
        }
    });
    holderNameTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            holderNameTxtBoxKeyTyped(evt);
        }
    });
    jPanel3.add(holderNameTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 600, 40));

    cardNoTxtBox.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
    cardNoTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            cardNoTxtBoxKeyTyped(evt);
        }
    });
    jPanel3.add(cardNoTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 600, 40));

    exDateTxtBox.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
    exDateTxtBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            exDateTxtBoxActionPerformed(evt);
        }
    });
    exDateTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            exDateTxtBoxKeyTyped(evt);
        }
    });
    jPanel3.add(exDateTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 290, 40));

    cvvTxtBox.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
    cvvTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            cvvTxtBoxKeyTyped(evt);
        }
    });
    jPanel3.add(cvvTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 290, 40));

    jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    jLabel11.setText("CVV");
    jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 120, 20));

    jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    jLabel13.setText("CARD HOLDER NAME");
    jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 20));

    jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    jLabel14.setText("CARD NUMBER");
    jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 160, 20));

    jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    jLabel15.setText("EXPIRE DATE");
    jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, 20));

    buttonGroup1.add(visaCardRadioBtn);
    visaCardRadioBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    visaCardRadioBtn.setText("VISA CARD");
    jPanel3.add(visaCardRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 240, -1));

    jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel12.setText("SELECT PAYMENT METHOD :-");
    jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 20));

    buttonGroup1.add(masterCardRadioBtn);
    masterCardRadioBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    masterCardRadioBtn.setText("MASTER CARD");
    jPanel3.add(masterCardRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 200, -1));

    getOtpBTn.setBackground(new java.awt.Color(102, 102, 102));
    getOtpBTn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    getOtpBTn.setText("GET OTP");
    getOtpBTn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 2, true));
    getOtpBTn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            getOtpBTnActionPerformed(evt);
        }
    });
    jPanel3.add(getOtpBTn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 160, 40));

    otpTxtBox.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
    otpTxtBox.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            otpTxtBoxKeyTyped(evt);
        }
    });
    jPanel3.add(otpTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 410, 40));

    jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    jLabel16.setText("Enter OTP");
    jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 120, 20));

    jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 640, 390));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1220, 500));

    backBtn.setBackground(new java.awt.Color(204, 204, 204));
    backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_left_arrow_24px_2.png"))); // NOI18N
    backBtn.setToolTipText("Back");
    backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            backBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            backBtnMouseExited(evt);
        }
    });
    backBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backBtnActionPerformed(evt);
        }
    });
    jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 100, 20));

    logOutBtn.setBackground(new java.awt.Color(204, 204, 204));
    logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    logOutBtn.setText("LOG OUT");
    logOutBtn.setToolTipText("LogOut");
    logOutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            logOutBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            logOutBtnMouseExited(evt);
        }
    });
    logOutBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logOutBtnActionPerformed(evt);
        }
    });
    jPanel1.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 100, 20));

    closeBtn1.setBackground(new java.awt.Color(204, 204, 204));
    closeBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    closeBtn1.setText("CLOSE");
    closeBtn1.setToolTipText("Close App");
    closeBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    closeBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            closeBtn1MouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            closeBtn1MouseExited(evt);
        }
    });
    closeBtn1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeBtn1ActionPerformed(evt);
        }
    });
    jPanel1.add(closeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, 100, 20));

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("STUDENT PROFILE :-");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 160, 20));

    stdIDLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    stdIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    stdIDLable.setText("STUDENT ID");
    jPanel1.add(stdIDLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 160, 20));

    jLabel1.setToolTipText("Student ID");
    jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 340, 20));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 580));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new StudentProfile(stdIDLable.getText()).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "DO YOU WANT TO LOGOUT?") == JOptionPane.YES_NO_OPTION) {
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void closeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtn1ActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "DO YOU WANT TO EXIT") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeBtn1ActionPerformed

    private void clearAllBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllBtnActionPerformed
        JFrame f = new JFrame();

        if (JOptionPane.showConfirmDialog(null, "Do you want to clear?") == JOptionPane.YES_NO_OPTION) {
            subTotalTxtBox.setText("");
            feeTxtBox.setText("");
            

            DefaultTableModel df = (DefaultTableModel) cartTable.getModel();
            int rc = df.getRowCount();
            for (int i = rc - 1; i >= 0; i--) {
                df.removeRow(i);
            }
        }
    }//GEN-LAST:event_clearAllBtnActionPerformed

    private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payBtnActionPerformed
        if (holderNameTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your cardholder name");
            holderNameTxtBox.grabFocus();
        } else if (cardNoTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter your card number");
            cardNoTxtBox.grabFocus();
        } else if (exDateTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter card expire date");
            exDateTxtBox.grabFocus();
        } else if (cvvTxtBox.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter card CVV");
            cvvTxtBox.grabFocus();
        } else {

            if (otp == 0) {
                JOptionPane.showConfirmDialog(null, "Please get the otp");
            } else {
                if (Integer.parseInt(otpTxtBox.getText()) == otp) {
                    if (Payments.doPayment(ranVal, Double.parseDouble(subTotalTxtBox.getText()))) {

                        JOptionPane.showMessageDialog(null, "Payment SuccessFull");

                        try {
                            String[] fields = {"Course", "Fee"};
                            DefaultTableModel df = new DefaultTableModel(fields, 0);
                            int rowC = df.getRowCount();
                            for (int i = 0; i < rowC; i++) {
                                Vector v = new Vector();
                                v.add(cartTable.getValueAt(i, 0));
                                v.add(cartTable.getValueAt(i, 1));
                                df.addRow(v);
                            }

                            String pMethod = "";
                            if (visaCardRadioBtn.isSelected()) {
                                pMethod = "Visa Card";
                            } else if (masterCardRadioBtn.isSelected()) {
                                pMethod = "Master Card";
                            }

                            HashMap parameter = new HashMap();
                            parameter.put("studentID", stdIDLable.getText());
                            parameter.put("paymentID", stdIDLable.getText());
                            parameter.put("date", dateLable.getText());
                            parameter.put("time", timeLable.getText());
                            parameter.put("total", "LKR " + subTotalTxtBox.getText());
                            parameter.put("paymentMethod", pMethod);

                            JRDataSource drs = new JRTableModelDataSource(df);
                            JasperPrint printBill = JasperFillManager.fillReport("invoice.jrxml", parameter, drs);
                            JasperViewer.viewReport(printBill, false);

                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Payment Process Canceld");
                    }
                } else {
                    JOptionPane.showConfirmDialog(null, "Incorrct OTP");
                }
            }
        }

    }//GEN-LAST:event_payBtnActionPerformed

    private void addToPayBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToPayBtn1MouseEntered
        addToPayBtn1.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_addToPayBtn1MouseEntered

    private void addToPayBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addToPayBtn1MouseExited
        addToPayBtn1.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_addToPayBtn1MouseExited

    private void clearAllBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearAllBtnMouseEntered
        clearAllBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_clearAllBtnMouseEntered

    private void clearAllBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearAllBtnMouseExited
        clearAllBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_clearAllBtnMouseExited

    private void removeCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCourseBtnMouseEntered
        removeCourseBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_removeCourseBtnMouseEntered

    private void removeCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeCourseBtnMouseExited
        removeCourseBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_removeCourseBtnMouseExited

    private void payBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBtnMouseEntered
        payBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_payBtnMouseEntered

    private void payBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payBtnMouseExited
        payBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_payBtnMouseExited

    private void closeBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseEntered
        closeBtn1.setBackground(Color.red);
    }//GEN-LAST:event_closeBtn1MouseEntered

    private void closeBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseExited
        closeBtn1.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_closeBtn1MouseExited

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(Color.red);
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(Color.red);
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_backBtnMouseExited

    private void addToPayBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToPayBtn1ActionPerformed
        if (coursesCmbBox.getSelectedItem().equals("Course List")) {
            JOptionPane.showMessageDialog(null, "Please Select a course");
        } else {

            String tblCourseName = "";

            DefaultTableModel df = (DefaultTableModel) cartTable.getModel();
            int rowC = df.getRowCount();
            for (int i = 0; i < 10; i++) {
                tblCourseName = df.getValueAt(i, 0).toString();
            }
            if (coursesCmbBox.getSelectedItem().toString().equals(tblCourseName)) {
                JOptionPane.showMessageDialog(null, "Already in the cart");
            } else {
                String[] data = {coursesCmbBox.getSelectedItem().toString(), feeTxtBox.getText()};
                df.addRow(data);
                
                setTotal();

            }
        }
    }//GEN-LAST:event_addToPayBtn1ActionPerformed

    private void holderNameTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holderNameTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_holderNameTxtBoxActionPerformed

    private void exDateTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exDateTxtBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exDateTxtBoxActionPerformed

    private void holderNameTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_holderNameTxtBoxKeyTyped
        if ((visaCardRadioBtn.isSelected() || masterCardRadioBtn.isSelected())) {

        } else {
            JOptionPane.showMessageDialog(null, "Please select a paymant method");
            evt.consume();
        }
    }//GEN-LAST:event_holderNameTxtBoxKeyTyped

    private void cardNoTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNoTxtBoxKeyTyped
        if ((visaCardRadioBtn.isSelected() || masterCardRadioBtn.isSelected())) {

        } else {
            JOptionPane.showMessageDialog(null, "Please select a paymant method");
            evt.consume();
        }

        char c = evt.getKeyChar();
        if ((c < '0') || (c > '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Only numbers are accepted");
        }
    }//GEN-LAST:event_cardNoTxtBoxKeyTyped

    private void exDateTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exDateTxtBoxKeyTyped
        if ((visaCardRadioBtn.isSelected() || masterCardRadioBtn.isSelected())) {

        } else {
            JOptionPane.showMessageDialog(null, "Please select a paymant method");
            evt.consume();
        }

        char c = evt.getKeyChar();
        if ((c < '0') || (c > '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Only numbers are accepted");
        }
    }//GEN-LAST:event_exDateTxtBoxKeyTyped

    private void cvvTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvTxtBoxKeyTyped
        if ((visaCardRadioBtn.isSelected() || masterCardRadioBtn.isSelected())) {

        } else {
            JOptionPane.showMessageDialog(null, "Please select a paymant method");
            evt.consume();
        }

        char c = evt.getKeyChar();
        if ((c < '0') || (c > '9')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Only numbers are accepted");
        }
    }//GEN-LAST:event_cvvTxtBoxKeyTyped

    private void coursesCmbBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_coursesCmbBoxItemStateChanged
        try {

            String query = "select * from course where CourseTitle = '" + coursesCmbBox.getSelectedItem() + "'";
            ResultSet rs = MyConn.search(query);

            while (rs.next()) {
                feeTxtBox.setText(rs.getString("Fee"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_coursesCmbBoxItemStateChanged

    private void otpTxtBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otpTxtBoxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_otpTxtBoxKeyTyped

    private void getOtpBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getOtpBTnActionPerformed
        otpGenarator();

        OTPWriter.otpGen(stdIDLable.getText(), otp, "Make your Payment");
    }//GEN-LAST:event_getOtpBTnActionPerformed

    private void removeCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCourseBtnActionPerformed
        DefaultTableModel df = (DefaultTableModel) cartTable.getModel();

        if (cartTable.getSelectedRowCount() == 1) {
            df.removeRow(cartTable.getSelectedRow());
            setTotal();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a course to Delete");
        }
    }//GEN-LAST:event_removeCourseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakePaymentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakePaymentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakePaymentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakePaymentsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakePaymentsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToPayBtn1;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cardNoTxtBox;
    private javax.swing.JTable cartTable;
    private javax.swing.JButton clearAllBtn;
    private javax.swing.JButton closeBtn1;
    private javax.swing.JComboBox<String> coursesCmbBox;
    private javax.swing.JTextField cvvTxtBox;
    private javax.swing.JLabel dateLable;
    private javax.swing.JTextField exDateTxtBox;
    private javax.swing.JTextField feeTxtBox;
    private javax.swing.JButton getOtpBTn;
    private javax.swing.JTextField holderNameTxtBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JRadioButton masterCardRadioBtn;
    private javax.swing.JTextField otpTxtBox;
    private javax.swing.JButton payBtn;
    private javax.swing.JButton removeCourseBtn;
    private javax.swing.JLabel stdIDLable;
    private javax.swing.JTextField subTotalTxtBox;
    private javax.swing.JLabel timeLable;
    private javax.swing.JRadioButton visaCardRadioBtn;
    // End of variables declaration//GEN-END:variables
}
