/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentpayments;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ClassFiles.MyConn;
import java.sql.ResultSet;
import java.awt.Color;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dinis
 */
public class registerCourseFrame extends javax.swing.JFrame {

    /**
     * Creates new form registerCourseFrame
     */
    
    public registerCourseFrame(String stdId) {
        initComponents();
        stdIDTxtBox.setText(stdId);
        
        loadCourses();
        adjustTbColums();
    }
    
    public void loadCourses() {

        try {
            String load = "select * from course";
            ResultSet rs = MyConn.search(load);

            DefaultTableModel df = (DefaultTableModel) availableCourseTable.getModel();
            int rowC = df.getRowCount();

            for (int i = 0; i < rowC; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("courseTitle"));
                v.add(rs.getString("Duration"));
                v.add(rs.getString("Fee"));
                v.add(rs.getString("NeedToPay"));
                df.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void adjustTbColums() {

        availableCourseTable.getColumnModel().getColumn(0).setPreferredWidth(200);
        availableCourseTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        availableCourseTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        availableCourseTable.getColumnModel().getColumn(3).setPreferredWidth(100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableCourseTable = new javax.swing.JTable();
        JLable1 = new javax.swing.JLabel();
        selectedCourseTxtBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        registerBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        stdIDTxtBox = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        closeBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        availableCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course Title", "Duration", "Fee", "Need to Pay"
            }
        )
        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }
    );
    availableCourseTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            availableCourseTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(availableCourseTable);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, 616, 460));

    JLable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    JLable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    JLable1.setText("SELECT A COURSE TO REGISETR");
    jPanel1.add(JLable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 610, 20));

    jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 20, 630, 520));

    selectedCourseTxtBox.setEditable(false);
    selectedCourseTxtBox.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    selectedCourseTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
    selectedCourseTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
    jPanel2.add(selectedCourseTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 580, 40));

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel5.setText("SELECTED COURSE :-");
    jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 580, 20));

    jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
    jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
    jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1240, 10));

    registerBtn.setBackground(new java.awt.Color(204, 204, 204));
    registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    registerBtn.setText("REGISTER");
    registerBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
    registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            registerBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            registerBtnMouseExited(evt);
        }
    });
    registerBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            registerBtnActionPerformed(evt);
        }
    });
    jPanel2.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 580, 30));

    jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel9.setText("STUDENT ID :-");
    jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 580, 20));

    stdIDTxtBox.setEditable(false);
    stdIDTxtBox.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
    stdIDTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
    stdIDTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
    jPanel2.add(stdIDTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 580, 40));

    backBtn.setBackground(new java.awt.Color(204, 204, 204));
    backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_left_arrow_24px_2.png"))); // NOI18N
    backBtn.setToolTipText("Back");
    backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            backBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            backBtnMouseExited(evt);
        }
    });
    backBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backBtnActionPerformed(evt);
        }
    });
    jPanel2.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 100, 20));

    logOutBtn.setBackground(new java.awt.Color(204, 204, 204));
    logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    logOutBtn.setText("LOG OUT");
    logOutBtn.setToolTipText("LogOut");
    logOutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            logOutBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            logOutBtnMouseExited(evt);
        }
    });
    logOutBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logOutBtnActionPerformed(evt);
        }
    });
    jPanel2.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 100, 20));

    closeBtn1.setBackground(new java.awt.Color(204, 204, 204));
    closeBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    closeBtn1.setText("CLOSE");
    closeBtn1.setToolTipText("Close App");
    closeBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    closeBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            closeBtn1MouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            closeBtn1MouseExited(evt);
        }
    });
    closeBtn1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeBtn1ActionPerformed(evt);
        }
    });
    jPanel2.add(closeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, 100, 20));

    getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 580));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseEntered
        registerBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_registerBtnMouseEntered

    private void registerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseExited
        registerBtn.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_registerBtnMouseExited

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(Color.red);
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new StudentProfile(stdIDTxtBox.getText()).setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(Color.red);
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "DO YOU WANT TO LOGOUT?") == JOptionPane.YES_NO_OPTION) {
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void closeBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseEntered
        closeBtn1.setBackground(Color.red);
    }//GEN-LAST:event_closeBtn1MouseEntered

    private void closeBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseExited
        closeBtn1.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_closeBtn1MouseExited

    private void closeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtn1ActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "DO YOU WANT TO EXIT") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeBtn1ActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        try {
            if (selectedCourseTxtBox.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Please select a course to register");
            } else if (stdIDTxtBox.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Please Enter the studentID");
            }else{
                JFrame f = new JFrame();
                if (JOptionPane.showConfirmDialog(f, "Is all the details Correct?") == JOptionPane.YES_NO_OPTION) {
                    
                    DefaultTableModel df = (DefaultTableModel) availableCourseTable.getModel();
                    
                    String courseID = "";
                    String courseTitle = df.getValueAt(availableCourseTable.getSelectedRow(), 0).toString();
                    
                    String getCID = "Select * from course where CourseTitle = '"+courseTitle+"'";
                    ResultSet rs = MyConn.search(getCID);
                    while (rs.next()) {                        
                        courseID = rs.getString("CourseID");
                    }
                    
                    String register = "Update course set student_studentID = '"+stdIDTxtBox.getText()+"' where CourseTitle = '"+courseTitle+"'";
                    MyConn.save(register);
                    JOptionPane.showMessageDialog(null, "Successfully Registerd");
                    
                } else {
                    JOptionPane.showMessageDialog(null,"Registration Canceld");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void availableCourseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableCourseTableMouseClicked
        DefaultTableModel df = (DefaultTableModel) availableCourseTable.getModel();
        
        selectedCourseTxtBox.setText(df.getValueAt(availableCourseTable.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_availableCourseTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerCourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerCourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerCourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerCourseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerCourseFrame("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLable1;
    private javax.swing.JTable availableCourseTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton closeBtn1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField selectedCourseTxtBox;
    private javax.swing.JTextField stdIDTxtBox;
    // End of variables declaration//GEN-END:variables
}
