/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentpayments;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ClassFiles.MyConn;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dinis
 */
public class StudentProfile extends javax.swing.JFrame {

    /**
     * Creates new form StudentProfile
     */
    String stdID = "";

    public StudentProfile(String stdID) {
        initComponents();

        date();
        time();
        showCourses();
        showPaymentHistory();

        this.stdID = stdID;
        stdIDLable.setText(stdID);
    }

    // This method vill show the date to the user
    public void date() {
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy/MM/dd");
        dateLable.setText(df.format(d));
    }

    //This method will show the current time to the user
    public void time() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a");
                timeLable.setText(df.format(d));
            }
        }).start();
    }

    public void showCourses() {
        try {

            String getCourseID = "select * from course where student_StudentID = '" + stdIDLable.getText() + "'";
            ResultSet rs = MyConn.search(getCourseID);

            DefaultTableModel df = (DefaultTableModel) coursesTable.getModel();
            int rowC = df.getRowCount();
            for (int i = 0; i < rowC; i++) {
                df.removeRow(0);
            }
            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("CourseTitle"));
                df.addRow(v);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void showPaymentHistory() {
        try {
            String courseID = "";
            String getDetails = "select * from payment where student_StudentID = '" + stdID + "'";
            ResultSet rs1 = MyConn.search(getDetails);

            DefaultTableModel df = (DefaultTableModel) paymentHistoryTable.getModel();
            int rowC = df.getRowCount();
            for (int i = 0; i < rowC; i++) {
                df.removeRow(0);
            };
            while (rs1.next()) {
                String getCourseDetails = "select * from course where CourseID = '" + courseID + "'";
                ResultSet rs2 = MyConn.search(getCourseDetails);
                Vector v = new Vector();
                while (rs2.next()) {
                    v.add(rs2.getString("CourseTitle"));
                    v.add(rs2.getString("Fee"));
                }

                v.add(rs1.getString("Date"));
                v.add(rs1.getString("Time"));

                df.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateLable = new javax.swing.JLabel();
        timeLable = new javax.swing.JLabel();
        stdIDLable = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentHistoryTable = new javax.swing.JTable();
        getReportBtn = new javax.swing.JButton();
        makePaymentBtn = new javax.swing.JButton();
        changePwdBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursesTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        registerCourseBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        closeBtn1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLable.setText("Date");
        dateLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel1.add(dateLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        timeLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLable.setText("Time");
        timeLable.setToolTipText("Time");
        timeLable.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jPanel1.add(timeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 120, 20));

        stdIDLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stdIDLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stdIDLable.setText("STUDENT ID");
        jPanel1.add(stdIDLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 160, 20));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(3, 3, 3), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(51, 51, 51)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PAYMENT HISTORY");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 20));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 370, 20));

        paymentHistoryTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paymentHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Amount", "Date", "Time"
            }
        )

        {
            public boolean isCellEditable(int row, int column){
                return false;
            }
        }

    );
    paymentHistoryTable.setToolTipText("Your Payments");
    jScrollPane1.setViewportView(paymentHistoryTable);

    jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 590, 370));

    getReportBtn.setBackground(new java.awt.Color(204, 204, 204));
    getReportBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    getReportBtn.setText("GET REPORT");
    getReportBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
    getReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            getReportBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            getReportBtnMouseExited(evt);
        }
    });
    getReportBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            getReportBtnActionPerformed(evt);
        }
    });
    jPanel3.add(getReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 590, 30));

    jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 610, 470));

    makePaymentBtn.setBackground(new java.awt.Color(204, 204, 204));
    makePaymentBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    makePaymentBtn.setText("MAKE A PAYMENT");
    makePaymentBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    makePaymentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            makePaymentBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            makePaymentBtnMouseExited(evt);
        }
    });
    makePaymentBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            makePaymentBtnActionPerformed(evt);
        }
    });
    jPanel2.add(makePaymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 560, 30));

    changePwdBtn.setBackground(new java.awt.Color(204, 204, 204));
    changePwdBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    changePwdBtn.setText("CHANGE PASSWORD");
    changePwdBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    changePwdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            changePwdBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            changePwdBtnMouseExited(evt);
        }
    });
    changePwdBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            changePwdBtnActionPerformed(evt);
        }
    });
    jPanel2.add(changePwdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 560, 30));

    coursesTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    coursesTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "CourseTitle"
        }
    ) {
        boolean[] canEdit = new boolean [] {
            false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    coursesTable.setToolTipText("Your Courses");
    jScrollPane2.setViewportView(coursesTable);
    if (coursesTable.getColumnModel().getColumnCount() > 0) {
        coursesTable.getColumnModel().getColumn(0).setResizable(false);
    }

    jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 560, 280));

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel5.setText("YOUR COURSES :-");
    jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 560, 20));

    registerCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
    registerCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    registerCourseBtn.setText("REGISTER FOR A COURSE");
    registerCourseBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    registerCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            registerCourseBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            registerCourseBtnMouseExited(evt);
        }
    });
    registerCourseBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            registerCourseBtnActionPerformed(evt);
        }
    });
    jPanel2.add(registerCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 560, 30));

    jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1220, 500));

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("STUDENT PROFILE :-");
    jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 160, 20));

    jLabel1.setToolTipText("Student ID");
    jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 340, 20));

    closeBtn1.setBackground(new java.awt.Color(204, 204, 204));
    closeBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    closeBtn1.setText("CLOSE");
    closeBtn1.setToolTipText("Close App");
    closeBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    closeBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            closeBtn1MouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            closeBtn1MouseExited(evt);
        }
    });
    closeBtn1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeBtn1ActionPerformed(evt);
        }
    });
    jPanel1.add(closeBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, 100, 20));

    backBtn.setBackground(new java.awt.Color(204, 204, 204));
    backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_left_arrow_24px_2.png"))); // NOI18N
    backBtn.setToolTipText("Back");
    backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            backBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            backBtnMouseExited(evt);
        }
    });
    backBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            backBtnActionPerformed(evt);
        }
    });
    jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 100, 20));

    logOutBtn.setBackground(new java.awt.Color(204, 204, 204));
    logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    logOutBtn.setText("LOG OUT");
    logOutBtn.setToolTipText("LogOut");
    logOutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
    logOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            logOutBtnMouseEntered(evt);
        }
        public void mouseExited(java.awt.event.MouseEvent evt) {
            logOutBtnMouseExited(evt);
        }
    });
    logOutBtn.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            logOutBtnActionPerformed(evt);
        }
    });
    jPanel1.add(logOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 100, 20));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 580));

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "DO YOU WANT TO LOGOUT?") == JOptionPane.YES_NO_OPTION) {
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void closeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtn1ActionPerformed
        JFrame f = new JFrame();
        if (JOptionPane.showConfirmDialog(f, "DO YOU WANT TO EXIT") == JOptionPane.YES_NO_OPTION) {
            java.lang.System.exit(0);
        }
    }//GEN-LAST:event_closeBtn1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void makePaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makePaymentBtnActionPerformed
        this.dispose();
        new MakePaymentsFrame().setVisible(true);
    }//GEN-LAST:event_makePaymentBtnActionPerformed

    private void registerCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerCourseBtnActionPerformed
        this.dispose();
        new registerCourseFrame(stdIDLable.getText()).setVisible(true);
    }//GEN-LAST:event_registerCourseBtnActionPerformed

    private void changePwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdBtnActionPerformed

        new ForgotPasswordFrame(stdIDLable.getText()).setVisible(true);
    }//GEN-LAST:event_changePwdBtnActionPerformed

    private void makePaymentBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makePaymentBtnMouseEntered
        makePaymentBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_makePaymentBtnMouseEntered

    private void makePaymentBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makePaymentBtnMouseExited
        makePaymentBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_makePaymentBtnMouseExited

    private void registerCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerCourseBtnMouseEntered
        registerCourseBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_registerCourseBtnMouseEntered

    private void registerCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerCourseBtnMouseExited
        registerCourseBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_registerCourseBtnMouseExited

    private void changePwdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePwdBtnMouseEntered
        changePwdBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_changePwdBtnMouseEntered

    private void changePwdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePwdBtnMouseExited
        changePwdBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_changePwdBtnMouseExited

    private void closeBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseEntered
        closeBtn1.setBackground(Color.red);
    }//GEN-LAST:event_closeBtn1MouseEntered

    private void closeBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtn1MouseExited
        closeBtn1.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_closeBtn1MouseExited

    private void logOutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseEntered
        logOutBtn.setBackground(Color.red);
    }//GEN-LAST:event_logOutBtnMouseEntered

    private void logOutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutBtnMouseExited
        logOutBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_logOutBtnMouseExited

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        backBtn.setBackground(Color.red);
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        backBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_backBtnMouseExited

    private void getReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getReportBtnMouseEntered
        getReportBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_getReportBtnMouseEntered

    private void getReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getReportBtnMouseExited
        getReportBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_getReportBtnMouseExited

    private void getReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getReportBtnActionPerformed
        try {
            String[] fieldNames = {"Course", "Amount", "Date", "Time"};
            DefaultTableModel df = new DefaultTableModel(fieldNames, 0);
            int a = paymentHistoryTable.getRowCount();
            for (int i = 0; i < a; i++) {
                Vector v = new Vector();
                v.add(paymentHistoryTable.getValueAt(i, 0));
                v.add(paymentHistoryTable.getValueAt(i, 1));
                v.add(paymentHistoryTable.getValueAt(i, 2));
                v.add(paymentHistoryTable.getValueAt(i, 3));
                df.addRow(v);
            }
            
            HashMap params = new HashMap();
            params.put("StudentID", stdIDLable.getText());
            params.put("createdDate", dateLable.getText());
            
            JRDataSource jrs = new JRTableModelDataSource(df);
            JasperPrint print = JasperFillManager.fillReport("PaymentHistory.jrxml", params, jrs);
            JasperViewer.viewReport(print, false);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_getReportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton changePwdBtn;
    private javax.swing.JButton closeBtn1;
    private javax.swing.JTable coursesTable;
    private javax.swing.JLabel dateLable;
    private javax.swing.JButton getReportBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton makePaymentBtn;
    private javax.swing.JTable paymentHistoryTable;
    private javax.swing.JButton registerCourseBtn;
    private javax.swing.JLabel stdIDLable;
    private javax.swing.JLabel timeLable;
    // End of variables declaration//GEN-END:variables
}
