/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentpayments;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ClassFiles.MyConn;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinis
 */
public class updateCoursePanel1 extends javax.swing.JPanel {

    /**
     * Creates new form addNewCoursePanel
     */
    public updateCoursePanel1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        courseTitleTxtBox = new javax.swing.JTextField();
        updateCourseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseListTable = new javax.swing.JTable();
        durationTxtBox1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        monthlyRadioBtn = new javax.swing.JRadioButton();
        yearlyradioBtn = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "UPDATE COURSE PANEL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("COURSE TITLE:-");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 120, 30));

        courseTitleTxtBox.setBackground(new java.awt.Color(204, 204, 204));
        courseTitleTxtBox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        courseTitleTxtBox.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        add(courseTitleTxtBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 570, 30));

        updateCourseBtn.setBackground(new java.awt.Color(204, 204, 204));
        updateCourseBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateCourseBtn.setText("UPDATE COURSE");
        updateCourseBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        updateCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateCourseBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateCourseBtnMouseExited(evt);
            }
        });
        updateCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCourseBtnActionPerformed(evt);
            }
        });
        add(updateCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 570, 50));

        courseListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Title", "Duration", "Need to Pay"
            }
        ));
        jScrollPane1.setViewportView(courseListTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 150));

        durationTxtBox1.setBackground(new java.awt.Color(204, 204, 204));
        durationTxtBox1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        durationTxtBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        add(durationTxtBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 570, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("NEED TO PAY:-");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("DURATION:-");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 30));

        monthlyRadioBtn.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(monthlyRadioBtn);
        monthlyRadioBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        monthlyRadioBtn.setText("MONTHLY");
        add(monthlyRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 30));

        yearlyradioBtn.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(yearlyradioBtn);
        yearlyradioBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yearlyradioBtn.setText("YEARLY");
        add(yearlyradioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void updateCourseBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCourseBtnMouseEntered
        updateCourseBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_updateCourseBtnMouseEntered

    private void updateCourseBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCourseBtnMouseExited
        updateCourseBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_updateCourseBtnMouseExited

    private void updateCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCourseBtnActionPerformed
        try {
            if (courseTitleTxtBox.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter the course Title");
                courseTitleTxtBox.grabFocus();
            } else if (durationTxtBox1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter the course duration");
            } else {

                DefaultTableModel df = (DefaultTableModel) courseListTable.getModel();

                JFrame f = new JFrame();
                if (JOptionPane.showConfirmDialog(f, "Are all the details correct") == JOptionPane.YES_NO_OPTION) {

                    String needToPay = "";
                    if (monthlyRadioBtn.isSelected()) {
                        needToPay = "Monthly";
                    } else if (yearlyradioBtn.isSelected()) {
                        needToPay = "Yearly";
                    }

                    String courseID = courseListTable.getValueAt(courseListTable.getSelectedRow(), 0).toString();
                    String upCourse = "update course set CourseTitle = '" + courseTitleTxtBox.getText() + "', Duration = '" + durationTxtBox1.getText() + "', NeedToPay = '" + needToPay + "' where CourseID = '" + courseID + "'";
                    MyConn.save(upCourse);
                    JOptionPane.showMessageDialog(null, "UpDated");

                } else {
                    JOptionPane.showMessageDialog(null, "Did not updated");

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_updateCourseBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTable courseListTable;
    private javax.swing.JTextField courseTitleTxtBox;
    private javax.swing.JTextField durationTxtBox1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton monthlyRadioBtn;
    private javax.swing.JButton updateCourseBtn;
    private javax.swing.JRadioButton yearlyradioBtn;
    // End of variables declaration//GEN-END:variables
}
