/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package studentpayments;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ClassFiles.MyConn;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dinis
 */
public class viewStdCourses extends javax.swing.JPanel {

    /**
     * Creates new form addNewCoursePanel
     */
    public viewStdCourses() {
        initComponents();

        loadCourses();
        adjustTbColums();

    }

    public void loadCourses() {

        try {
            String load = "select * from course";
            ResultSet rs = MyConn.search(load);

            DefaultTableModel df = (DefaultTableModel) courseList.getModel();
            int rowC = df.getRowCount();

            for (int i = 0; i < rowC; i++) {
                df.removeRow(0);
            }

            while (rs.next()) {

                Vector v = new Vector();
                v.add(rs.getString("courseID"));
                v.add(rs.getString("courseTitle"));
                v.add(rs.getString("Duration"));
                v.add(rs.getString("NeedToPay"));
                df.addRow(v);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void adjustTbColums() {

        courseList.getColumnModel().getColumn(0).setPreferredWidth(50);
        courseList.getColumnModel().getColumn(1).setPreferredWidth(200);
        courseList.getColumnModel().getColumn(2).setPreferredWidth(100);
        courseList.getColumnModel().getColumn(3).setPreferredWidth(100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseList = new javax.swing.JTable();
        getReportBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "COURSES & STUDENTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 10))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        courseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course ID", "Course Title", "Duration", "Need to Pay"
            }
        ));
        jScrollPane1.setViewportView(courseList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 340));

        getReportBtn.setBackground(new java.awt.Color(204, 204, 204));
        getReportBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getReportBtn.setText("GET REPORT");
        getReportBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 102)));
        getReportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                getReportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                getReportBtnMouseExited(evt);
            }
        });
        getReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getReportBtnActionPerformed(evt);
            }
        });
        add(getReportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 570, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void getReportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getReportBtnMouseEntered
        getReportBtn.setBackground(new Color(153, 153, 153));
    }//GEN-LAST:event_getReportBtnMouseEntered

    private void getReportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getReportBtnMouseExited
        getReportBtn.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_getReportBtnMouseExited

    private void getReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getReportBtnActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentpaymentsystem", "root", "Ransilu@123");
            JasperReport jr = JasperCompileManager.compileReport("Blank_A4_3.jrxml");
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp);
            
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_getReportBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable courseList;
    private javax.swing.JButton getReportBtn;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
